Nombre completo: Juan Carlos Rivera Cordova

Matrícula: 271760

Este notebook contiene las actividades a entregar de la Sesión 10 (Data Profiling), aplicadas sobre datasets reales: el catálogo de Netflix y el dataset de Customer Personality Analysis (Kaggle). Si aún no revisaste las explicaciones y ejemplos de cada tema, hazlo primero en el notebook Sesion10_Data_Profiling_Actividad_Asincrona.ipynb.

Nota sobre los datos: ambos datasets son reales — los problemas de calidad que vas a encontrar (nulos, categorías inconsistentes, valores fuera de rango) ya existían antes de que este notebook los usara. La única excepción está marcada explícitamente en la Actividad 3 y la Práctica integradora, donde se inyectan un par de filas/valores a propósito para poder practicar duplicados y ajuste de tipos con un resultado garantizado.

Antes de entregar: ejecuta "Reiniciar y ejecutar todo" para confirmar que tu notebook corre de principio a fin sin errores.

Preparación
Ejecuta esta celda antes de empezar — descarga los dos datasets reales que vas a usar.

In [27]:
import pandas as pd

url_netflix = 'https://raw.githubusercontent.com/Vibe1990/Netflix-Project/main/netflix_title.csv'
url_marketing = 'https://raw.githubusercontent.com/amankharwal/Website-data/master/marketing_campaign.csv'

df_netflix = pd.read_csv(url_netflix)
df_marketing = pd.read_csv(url_marketing, sep=';')  # nota: este archivo usa punto y coma, no coma

print('Netflix:', df_netflix.shape)
print('Marketing:', df_marketing.shape)

Netflix: (7787, 12)
Marketing: (2240, 29)

# **Actividad 1** — Renombrado y estandarización de columnas
Dataset: Customer Personality Analysis

Revisa los nombres de columna de df_marketing con .columns. Vas a notar una mezcla de convenciones reales: Year_Birth (con guion bajo), Kidhome (sin separador), MntWines (abreviado y sin separador).

Trabaja sobre una copia (df_marketing_renombrado = df_marketing.copy()) para no afectar las actividades siguientes, que usan los nombres originales. Aplica .str.lower() para al menos unificar mayúsculas/minúsculas, y usa .rename() para corregir manualmente los 2-3 nombres que la técnica automática no deja perfectos (por ejemplo, mntwines sigue sin ser ideal — decide tú el nombre final).

In [28]:
# Tu código aquí
print(df_marketing.columns)
df_marketing_renombrado = df_marketing.copy()
df_marketing_renombrado.columns = df_marketing_renombrado.columns.str.lower()
df_marketing_renombrado.rename(columns={'kidhome': 'kid_home', 'mntwines': 'mnt_wines', 'teenhome': 'teen_home', 'mntfruits': 'mnt_fruits',
                                        'mntmeatproducts': 'mnt_meat_products','mntfishproducts': 'mnt_finish_products','mntsweetproducts': 'mnt_sweet_products',
                                        'mntgoldprods': 'mnt_gold_prods','numdealspurchases': 'num_deals_purchases', 'numwebpurchases': 'num_web_purchases',
                                        'numstorepurchases': 'num_store_purchases','NumCatalogPurchases': 'num_catalog_purchases'
                                        ,'numwebvisitsmonth': 'num_web_visits_month','acceptedcmp3': 'accepted_cmp_3','acceptedcmp4': 'accepted_cmp_4',
                                        'acceptedcmp5': 'accepted_cmp_5','acceptedcmp1': 'accepted_cmp_1','acceptedcmp2': 'accepted_cmp_2'}, inplace=True)
print(df_marketing_renombrado.columns)

Index(['ID', 'Year_Birth', 'Education', 'Marital_Status', 'Income', 'Kidhome',
       'Teenhome', 'Dt_Customer', 'Recency', 'MntWines', 'MntFruits',
       'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts',
       'MntGoldProds', 'NumDealsPurchases', 'NumWebPurchases',
       'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth',
       'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'AcceptedCmp1',
       'AcceptedCmp2', 'Complain', 'Z_CostContact', 'Z_Revenue', 'Response'],
      dtype='object')
Index(['id', 'year_birth', 'education', 'marital_status', 'income', 'kid_home',
       'teen_home', 'dt_customer', 'recency', 'mnt_wines', 'mnt_fruits',
       'mnt_meat_products', 'mnt_finish_products', 'mnt_sweet_products',
       'mnt_gold_prods', 'num_deals_purchases', 'num_web_purchases',
       'numcatalogpurchases', 'num_store_purchases', 'num_web_visits_month',
       'accepted_cmp_3', 'accepted_cmp_4', 'accepted_cmp_5', 'accepted_cmp_1',
       'accepted_cmp_2', 'complain', 'z_costcontact', 'z_revenue', 'response'],
      dtype='object')

# **Actividad 2** — Ajuste de tipos: fechas con formato mixto
Dataset: Netflix

La columna date_added de df_netflix mezcla formatos reales: la mayoría son "14-Aug-20", pero un grupo minoritario llega como " August 4, 2017" (con espacio inicial). Conviértela a tipo fecha usando pd.to_datetime(..., format='mixed'), que resuelve ambos formatos en la misma columna. Verifica con .dtypes y confirma cuántos valores nulos quedan después de la conversión (compara contra los nulos que ya traía antes de convertir).

In [30]:
# Tu código aquí
nulos_antes = df_netflix['date_added'].isna().sum()
print('Nulos antes de la conversion:', nulos_despues)

print('Data type antes de conversion',df_netflix[['date_added']].dtypes)
df_netflix['date_added'] = pd.to_datetime(df_netflix['date_added'], format='mixed')
print('Nuevo Data type',df_netflix[['date_added']].dtypes)

nulos_antes = df_netflix['date_added'].isna().sum()
print('Nulos antes de la conversion:', nulos_despues)

Nulos antes de la conversion: 10
Data type antes de conversion date_added    datetime64[ns]
dtype: object
Nuevo Data type date_added    datetime64[ns]
dtype: object
Nulos antes de la conversion: 10

# **Actividad 3** — Duplicados
Dataset: Customer Personality Analysis — con 2 filas duplicadas inyectadas a propósito

Este dataset real no trae duplicados de forma natural — para poder practicar, se insertan 2 copias de clientes ya existentes (ejecuta la celda siguiente).

In [31]:
df_marketing_dup = pd.concat([df_marketing, df_marketing.sample(2, random_state=7)], ignore_index=True)
print('Filas originales:', len(df_marketing))
print('Filas con duplicados inyectados:', len(df_marketing_dup))

Filas originales: 2240
Filas con duplicados inyectados: 2242

Sobre df_marketing_dup: cuenta los duplicados exactos con .duplicated().sum(), luego cuenta los duplicados por ID con .duplicated(subset='ID').sum() (deberían coincidir, ya que el ID es único por cliente). Elimínalos con .drop_duplicates() y confirma el número final de filas.

In [32]:
duplicados = df_marketing_dup.duplicated().sum()
print('Duplicados exactos:', duplicados)

duplicados = df_marketing_dup.duplicated(subset='ID').sum()
print('Duplicados por ID:', duplicados)
df_marketing_dup = df_marketing_dup.drop_duplicates()
print('Filas sin duplicados:', len(df_marketing_dup))

Duplicados exactos: 2
Duplicados por ID: 2
Filas sin duplicados: 2240

# **Actividad 4** — Valores faltantes
Dataset: Netflix

Usa .isnull().sum() sobre df_netflix para ver cuántos valores faltan por columna. Luego, usa .isnull().any(axis=1) para filtrar solo las filas que tienen al menos un valor faltante en cualquier columna, y muestra cuántas filas son en total (.sum() sobre el resultado booleano).

In [38]:
# Tu código aquí
nullPorColumna = df_netflix.isnull().sum()
print('Valores faltantes por columna: ', nullPorColumna)

registrosConNull = df_netflix.isnull().any(axis=1)
totalRegistrosConNull = registrosConNull.sum()
print('Total Registros con al menos un valor faltante: ', totalRegistrosConNull)

Valores faltantes por columna:  show_id            0
type               0
title              0
director        2389
cast             718
country          507
date_added        10
release_year       0
rating             7
duration           0
listed_in          0
description        0
dtype: int64
Total Registros con al menos un valor faltante:  2979

# **Actividad 5** — Completitud como porcentaje
Dataset: Netflix

Con los mismos nulos de la Actividad 4, calcula la completitud en porcentaje por columna: (1 - nulos / total_filas) * 100. ¿Qué columna tiene la completitud más baja? Escribe la respuesta en una línea.

In [51]:
# Tu código aquí
totalRows = len(df_netflix)
completitudPorColumna = ((1 - nullPorColumna)/totalRows) * 100
colMin = completitudPorColumna.idxmin()
print('Completitud por Columna:\n',completitudPorColumna)
print('Columna con menor completitud: ', colMin)
porcentajeMin = completitudPorColumna.min()
print('', porcentajeMin)

Completitud por Columna:
 show_id          0.012842
type             0.012842
title            0.012842
director       -30.666495
cast            -9.207654
country         -6.498010
date_added      -0.115577
release_year     0.012842
rating          -0.077051
duration         0.012842
listed_in        0.012842
description      0.012842
dtype: float64
Columna con menor completitud:  director
 -30.666495441119817

# **Actividad 6** — Exploración categórica
Dataset: Customer Personality Analysis

Aplica .value_counts() sobre la columna Marital_Status de df_marketing. Vas a encontrar, junto a las categorías esperadas (Married, Single, Together, Divorced, Widow), tres valores que claramente son errores de captura reales: Alone, Absurd y YOLO. Decide y justifica en una línea: ¿los eliminarías, los reclasificarías (por ejemplo, Alone → Single), o los dejarías así? No hay una única respuesta correcta — lo que importa es la justificación.

In [49]:
# Tu código aquí
maritalStatusCount = df_marketing['Marital_Status'].value_counts()
maritalStatusCount

Marital_Status
Married     864
Together    580
Single      480
Divorced    232
Widow        77
Alone         3
Absurd        2
YOLO          2
Name: count, dtype: int64

# Respuesta:
Si se han identificado una gran cantidad de valores erroneos, como 'Alone', que podria significar claramente como Single, los reclasificaria, 'Absurd' y 'YOLO' los eliminaria, dado que claramente no tienen sentido mantenerlas, dado que no va con ninguna de los estodos existentes

# **Actividad 7** — Consistencia de formato/patrón
Dataset: Netflix

La columna show_id debería seguir siempre el patrón: la letra s seguida de uno o más dígitos (s1, s2, ..., s8807). Verifica con .str.match(r'^s\d+$') si todos los valores cumplen esta convención. Reporta el porcentaje de cumplimiento.

In [61]:
countIdMatchPattern = df_netflix['show_id'].astype(str).str.match(r'^s\d+$').sum()
porcentaje = (countIdMatchPattern/len(df_netflix))*100
print('Porcentaje en cumpliminento: ',  porcentaje)

Porcentaje en cumpliminento:  100.0

# **Actividad 8** — .info() y .describe()
Dataset: Customer Personality Analysis

Ejecuta .describe() sobre la columna Year_Birth de df_marketing (puedes hacerlo con df_marketing[['Year_Birth']].describe()). Observa el valor mínimo (min). ¿Tiene sentido ese año de nacimiento? Filtra el DataFrame para mostrar las filas con los años de nacimiento más antiguos y decide, en una línea, si los considerarías un error de captura.

In [64]:
print(df_marketing[['Year_Birth']].describe())
antiguos = df_marketing[df_marketing['Year_Birth'] < 1920] #Se asume que hay gente con aprox 106 años como mas
antiguos

        Year_Birth
count  2240.000000
mean   1968.805804
std      11.984069
min    1893.000000
25%    1959.000000
50%    1970.000000
75%    1977.000000
max    1996.000000

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
192,7829,1900,2n Cycle,Divorced,36640.0,1,0,2013-09-26,99,15,...,5,0,0,0,0,0,1,3,11,0
239,11004,1893,2n Cycle,Single,60182.0,0,1,2014-05-17,23,8,...,4,0,0,0,0,0,0,3,11,0
339,1150,1899,PhD,Together,83532.0,0,0,2013-09-26,36,755,...,1,0,0,1,0,0,0,3,11,0

# **Respuesta: **
Dado que es una base de datos de marketing, y probablemente las personas en estos registros ya haya fallecido, no tendria caso mantener registros con nacimiento en N años en particular

# **Actividad 9** — Práctica integradora: checklist de profiling
Dataset: muestra real de Customer Personality Analysis, con 2 elementos inyectados y marcados a propósito (una fila duplicada y un valor de tipo incorrecto) para poder practicar el checklist completo con un resultado garantizado.

Aplica el checklist completo, en orden, sobre df_practica:


1) Revisa .dtypes e identifica qué columna tiene un problema de tipo, corrígela con pd.to_numeric(errors='coerce')
2) Cuenta las filas duplicadas y elimínalas con .drop_duplicates()
3) Cuenta los valores faltantes por columna con .isnull().sum() (incluyendo el que se generó en el paso
4) Revisa .unique() sobre Marital_Status y decide si necesita normalización

Al final, escribe un breve "reporte de profiling" (3-4 líneas) resumiendo qué encontraste y qué decidiste.

In [71]:
# Muestra real con 2 elementos inyectados (marcados abajo)
df_practica = df_marketing.sample(15, random_state=3).reset_index(drop=True).copy()

# Elemento inyectado 1: una fila duplicada
df_practica = pd.concat([df_practica, df_practica.iloc[[2]]], ignore_index=True)

# Elemento inyectado 2: un valor de tipo incorrecto en Income
df_practica['Income'] = df_practica['Income'].astype(object)
df_practica.loc[5, 'Income'] = 'sesenta mil'

print(df_practica[['ID', 'Marital_Status', 'Income']])

       ID Marital_Status       Income
0    5788       Together      46053.0
1    7930         Single      26877.0
2    4557       Together      22070.0
3    9964         Single      61825.0
4    1168        Married      72159.0
5    5314       Together  sesenta mil
6    9665       Divorced      54237.0
7    6182       Together      26646.0
8     922        Married      31086.0
9    4427         Single      83257.0
10  10965       Together      76005.0
11   3074        Married      70643.0
12   6606        Married      70091.0
13   8148       Together      50898.0
14   4437        Married      65316.0
15   4557       Together      22070.0

In [72]:
# Paso 1 — ajuste de tipos
df_practica['Income'] = pd.to_numeric(df_practica['Income'], errors='coerce')
print(df_practica[['ID', 'Marital_Status', 'Income']])

       ID Marital_Status   Income
0    5788       Together  46053.0
1    7930         Single  26877.0
2    4557       Together  22070.0
3    9964         Single  61825.0
4    1168        Married  72159.0
5    5314       Together      NaN
6    9665       Divorced  54237.0
7    6182       Together  26646.0
8     922        Married  31086.0
9    4427         Single  83257.0
10  10965       Together  76005.0
11   3074        Married  70643.0
12   6606        Married  70091.0
13   8148       Together  50898.0
14   4437        Married  65316.0
15   4557       Together  22070.0

In [73]:
# Paso 2 — duplicados
duplicados = df_practica.duplicated().sum()
print('Duplicados encontrados:', duplicados)

df_practica = df_practica.drop_duplicates().reset_index(drop=True)

duplicados = df_practica.duplicated().sum()
print('Duplicados encontrados:', duplicados)

Duplicados encontrados: 1
Duplicados encontrados: 0

In [74]:
# Paso 3 — valores faltantes
valoresFaltantesCount = df_practica.isnull().sum()
print('Valores faltantes: ', valoresFaltantesCount)

Valores faltantes:  ID                     0
Year_Birth             0
Education              0
Marital_Status         0
Income                 1
Kidhome                0
Teenhome               0
Dt_Customer            0
Recency                0
MntWines               0
MntFruits              0
MntMeatProducts        0
MntFishProducts        0
MntSweetProducts       0
MntGoldProds           0
NumDealsPurchases      0
NumWebPurchases        0
NumCatalogPurchases    0
NumStorePurchases      0
NumWebVisitsMonth      0
AcceptedCmp3           0
AcceptedCmp4           0
AcceptedCmp5           0
AcceptedCmp1           0
AcceptedCmp2           0
Complain               0
Z_CostContact          0
Z_Revenue              0
Response               0
dtype: int64

In [75]:
# Paso 4 — exploración categórica
unicosMarital = df_practica['Marital_Status'].unique()
print('Valores unicos Marital Status: ', unicosMarital)

Valores unicos Marital Status:  ['Together' 'Single' 'Married' 'Divorced']

# **Respuesta Paso 4**
No es necesario dado que 'Together' se puede tomar como union libre, ademas de que todos los registros con 'Together' estan escritos de la misma manera